Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.9/3.9.13/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt

def puissiter(A,v0,lam,niter=50,epsilon = 1e-4):
    v = v0
    vv = [v0]
    l = np.dot(v0,np.dot(A,v0))
    ll = [l]
    epsilon = 1e-4
    k=0
    while np.fabs(lam-l)>epsilon and k<niter:
        w = np.dot(A,v)
        v = w/np.linalg.norm(w)
        l = np.dot(v,np.dot(A,v))
        vv.append(v)
        ll.append(l)
        k=k+1
    return ll, vv,k

A = np.array([[2.,1,-1],[1,3,1],[-1,1,4]])
lam =np.max(np.linalg.eigvals(A))
print("La plus grande valeur propre de A est ",lam)
ll, vv = puissiter(A,np.ones(3),lam)

plt.plot(range(len(ll)),ll,'-o',label='Puissances it√©r√©es')
plt.plot(range(len(ll)),lam*np.ones((len(ll)), dtype=np.uint8) ,'r')
plt.ylabel('valeur propre')
plt.xlabel('Iteration');
plt.legend()
plt.title("Valeur propre approch√©e √† ",epsilon,"pr√®s en ",k," it√©rations")
plt.tight_layout()



------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<module>[0;34m[0m
[1;32m     21[0m lam [38;5;241m=[39mnp[38;5;241m.[39mmax(np[38;5;241m.[39mlinalg[38;5;241m.[39meigvals(A))
[1;32m     22[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mLa plus grande valeur propre de A est [39m[38;5;124m"[39m,lam)
[0;32m---> 23[0m ll, vv [38;5;241m=[39m puissiter(A,np[38;5;241m.[39mones([38;5;241m3[39m),lam)
[1;32m     25[0m plt[38;5;241m.[39mplot([38;5;28mrange[39m([38;5;28mlen[39m(ll)),ll,[38;5;124m'[39m[38;5;124m-o[39m[38;5;124m'[39m,label[38;5;241m=[39m[38;5;124m'[39m[38;5;124mPuissances it√©r√©es[39m[38;5;124m'[39m)
[1;32m     26[0m plt[38;5;241m.[39mplot([38;5;28mrange[39m([38;5;28mlen[39m(ll)),lam[38;5;241m*[39mnp[38;5;241m.[39mones(([38;5;28mlen[39m(ll)), dtype[38;5;241m=[39mnp[38;5;241m.[39muint8) ,[38;5;124m'[39m[38;5;124mr[39m[38;5;124m'[39m)

[0;31mValueError[0m: too many values to unpack (expected 2)
ValueError: too many values to unpack (expected 2)

